### PR TITLE
allow-overriding-pathtype

### PR DESCRIPTION
**Pull request by franeksaww**
fix for: #62

### CODE REVIEW

**Comment by franeksaww** [comment]
@bdashrad fix for: https://github.com/PrivateBin/helm-chart/issues/62

**Review by bdashrad — CHANGES_REQUESTED** [review]
This needs a version bump to the chart version because it's a breaking change if you have changed the default values.

**Comment by bdashrad** [comment]
@franeksaww could you update the chart version in [Chart.yaml](https://github.com/PrivateBin/helm-chart/blob/master/charts/privatebin/Chart.yaml#L8) to `0.12.0` (assuming no other changes go in before this is merged)?

**Comment by bdashrad** [comment]
I want to make sure if we merge this, we are clear that it will break some existing installations because of the change to the `hosts` section under ingress.

**Comment by franeksaww** [comment]
Yes, only if someone will upgrade the chart to version 0.12.0

**Comment by franeksaww** [comment]
@bdashrad when there will be a possibility to merge this PR? Should I add some other changes?

**Review by bdashrad — APPROVED** [review]

**Pull request merged**
