### PR TITLE
fix(statefulset): remove duplicated securityContext key from template

### PR DESCRIPTION
**Pull request by glitchcrab**
This PR removes the duplicate securityContext from the statefulset template.

### CODE REVIEW

**Comment by elrido** [comment]
Wouldn't this need to be moved down to lines 50-51 instead of outright removed? AFAIK the fsGroup is needed to avoid having to chown the permissions in the attached volume...
https://github.com/PrivateBin/helm-chart/blob/c6813f6b662acb659e7b74f2c6bcc78d764f8463/charts/privatebin/templates/statefulset.yaml#L49-L52

**Comment by roy-urbint** [comment]
> Wouldn't this need to be moved down to lines 50-51 instead of outright removed? AFAIK the fsGroup is needed to avoid having to chown the permissions in the attached volume...
> 
> https://github.com/PrivateBin/helm-chart/blob/c6813f6b662acb659e7b74f2c6bcc78d764f8463/charts/privatebin/templates/statefulset.yaml#L49-L52

The PR is to remove duplicate entries of `securityContext` key under `spec`. The key is defined twice on line 36 and 39.

https://github.com/PrivateBin/helm-chart/blob/master/charts/privatebin/templates/statefulset.yaml#L36-L39

**Comment by bdashrad** [comment]
Please update the Chart.yaml to increment the patch version to 0.14.1 and I'll approve and merge.

**Comment by roy-urbint** [comment]
@glitchcrab Can you please do the changes and update the PR.

**Pull request closed without merging**
