### PR TITLE
Add v1 ingress support

### LINKED ISSUE #47: Migrate to networking.k8s.io/v1 Ingress
The extensions/v1beta1 and networking.k8s.io/v1beta1 API versions of Ingress are no longer served as of v1.22.

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

### PR DESCRIPTION
**Pull request by rlex**
Should close #47 
Better check on 1.21 and lower, since i only tested it on 1.22

### CODE REVIEW

**Comment by elrido** [comment]
The error reported by the chart linter is:

>  ✖︎ privatebin => (version: "0.8.0", path: "charts/privatebin") > Chart version not ok. Needs a version bump!

**Comment by bdashrad** [comment]
@rlex if you bump the chart version to 0.9.0 this should pass linting.

https://github.com/PrivateBin/helm-chart/blob/master/charts/privatebin/Chart.yaml#L8

**Comment by bdashrad** [comment]
Since kubernetes 1.18 is already EOL, i'd prefer to only make this change to support 1.19+. People on <1.19 can use the older chart or upgrade.

**Comment by rlex** [comment]
This PR should handle both pre-v1.22 k8s and v1.22+ with v1 ingress api, so users shouldn't have any issues with recent versions. Theoretically. I do not have older cluster to check. When v1 became available? 1.19?

**Comment by bdashrad** [comment]
@rlex Ingress moved to `networking.k8s.io/v1` in 1.19 and `networking.k8s.io/v1beta1` in 1.16. Since we only support and test 1.19 and greater, we don't need the conditional logic. 

The chart testing is still failing on the chart version not being incremented. Updating [here](https://github.com/PrivateBin/helm-chart/blob/master/charts/privatebin/Chart.yaml#L8) to 0.9.0 will fix this check.

**Comment by rlex** [comment]
seems to be passing now

**Pull request merged**
